[package]
name = "sodium_secretbox"
version = "0.1.0"
authors = ["Convex, Inc. <no-reply@convex.dev>"]
edition = "2021"
license = "LicenseRef-FSL-1.1-Apache-2.0"

[dependencies]
libsodium-sys-stable = { workspace = true }

[lints]
workspace = true
