[package]
name = "mysql"
version = "0.1.0"
authors = ["Convex, Inc. <no-reply@convex.dev>"]
edition = "2021"
license = "LicenseRef-FSL-1.1-Apache-2.0"

[lib]
doctest = false

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
common = { path = "../../crates/common" }
dynfmt = { workspace = true }
errors = { path = "../../crates/errors" }
fastrace = { workspace = true }
futures = { workspace = true }
futures-async-stream = { workspace = true }
hex = { workspace = true }
itertools = { workspace = true }
metrics = { path = "../../crates/metrics" }
mysql_async = { workspace = true }
prometheus = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
smallvec = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }

[dev-dependencies]
common = { path = "../../crates/common", features = ["testing"] }
errors = { path = "../../crates/errors", features = ["testing"] }
metrics = { path = "../../crates/metrics", features = ["testing"] }
runtime = { path = "../../crates/runtime" }

[features]
testing = [
    "common/testing",
    "errors/testing",
    "metrics/testing",
    "runtime/testing",
]

[lints]
workspace = true
