[package]
name = "mysql"
version = "0.1.0"
authors = ["Convex, Inc. <no-reply@convex.dev>"]
edition = "2024"
license = "LicenseRef-FSL-1.1-Apache-2.0"

[lib]
doctest = false

[features]
testing = [
    "common/testing",
    "errors/testing",
    "metrics/testing",
    "runtime/testing",
    "value/testing",
]

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
bytes = { workspace = true }
common = { workspace = true }
const_format = { workspace = true }
dynfmt = { workspace = true }
errors = { workspace = true }
fastrace = { workspace = true }
futures = { workspace = true }
futures-async-stream = { workspace = true }
hex = { workspace = true }
itertools = { workspace = true }
lz4_flex = { workspace = true }
metrics = { workspace = true }
mysql_async = { workspace = true }
prometheus = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
smallvec = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }
value = { workspace = true }

[dev-dependencies]
cmd_util = { workspace = true }
common = { workspace = true, features = ["testing"] }
errors = { workspace = true, features = ["testing"] }
metrics = { workspace = true, features = ["testing"] }
proptest = { workspace = true }
runtime = { workspace = true }
value = { workspace = true, features = ["testing"] }

[lints]
workspace = true
