[package]
name = "udf"
version = "0.1.0"
edition = "2024"
license = "LicenseRef-FSL-1.1-Apache-2.0"

[features]
testing = [
    "common/testing",
    "dep:proptest",
    "dep:proptest-derive",
    "dep:proptest-http",
    "value/testing",
    "sync_types/testing",
    "database/testing",
    "errors/testing",
    "keybroker/testing",
    "model/testing",
]

[dependencies]
anyhow = { workspace = true }
bytes = { workspace = true }
common = { workspace = true }
database = { workspace = true }
errors = { workspace = true }
fastrace = { workspace = true }
futures = { workspace = true }
headers = { workspace = true }
http = { workspace = true }
humansize = { workspace = true }
keybroker = { workspace = true }
mime = { workspace = true }
model = { workspace = true }
pb = { workspace = true }
proptest = { workspace = true, optional = true }
proptest-derive = { workspace = true, optional = true }
proptest-http = { workspace = true, optional = true }
rand = { workspace = true }
semver = { workspace = true }
serde_json = { workspace = true }
sync_types = { workspace = true }
tokio = { workspace = true }
url = { workspace = true }
value = { workspace = true }

[dev-dependencies]
cmd_util = { workspace = true }
common = { workspace = true, features = ["testing"] }
database = { workspace = true, features = ["testing"] }
errors = { workspace = true, features = ["testing"] }
keybroker = { workspace = true, features = ["testing"] }
model = { workspace = true, features = ["testing"] }
proptest = { workspace = true }
proptest-derive = { workspace = true }
proptest-http = { workspace = true }
sync_types = { workspace = true, features = [
    "testing",
] }
value = { workspace = true, features = ["testing"] }

[lints]
workspace = true
