[package]
name = "storage"
version = "0.1.0"
authors = ["Convex, Inc. <no-reply@convex.dev>"]
edition = "2024"
license = "LicenseRef-FSL-1.1-Apache-2.0"

[package.metadata.cargo-udeps.ignore]
normal = ["runtime"]
development = ["runtime"]

[lib]
doctest = false

[features]
testing = ["common/testing", "runtime/testing", "value/testing"]

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
axum = { workspace = true }
bytes = { workspace = true }
common = { workspace = true }
derive_more = { workspace = true }
fastrace = { workspace = true }
futures = { workspace = true }
futures-async-stream = { workspace = true }
http-body-util = { workspace = true }
pb = { workspace = true }
runtime = { workspace = true, optional = true }
serde_json = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tokio-util = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }
value = { workspace = true }

[dev-dependencies]
common = { workspace = true, features = ["testing"] }
convex_macro = { workspace = true }
parking_lot = { workspace = true }
runtime = { workspace = true, features = ["testing"] }
value = { workspace = true, features = ["testing"] }

[lints]
workspace = true
