[package]
name = "sqlite"
version = "0.1.0"
authors = ["Convex, Inc. <no-reply@convex.dev>"]
edition = "2024"
license = "LicenseRef-FSL-1.1-Apache-2.0"

[package.metadata.cargo-machete]
ignored = ["tokio"]

[lib]
doctest = false

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
common = { workspace = true }
futures = { workspace = true }
futures-async-stream = { workspace = true }
parking_lot = { workspace = true }
rusqlite = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
common = { workspace = true, features = ["testing"] }
tempfile = { workspace = true }
tokio = { workspace = true }

[lints]
workspace = true
