[package]
name = "value"
description = "Serverside value types supported by Convex (convex.dev)"
version = "0.1.0"
authors = ["Convex, Inc. <no-reply@convex.dev>"]
edition = "2021"
license = "LicenseRef-FSL-1.1-Apache-2.0"

[lib]
doctest = false

[dependencies]
anyhow = { workspace = true }
base-62 = { workspace = true }
base64 = { workspace = true }
byteorder = { workspace = true }
bytes = { workspace = true }
derive_more = { workspace = true }
errors = { path = "../errors" }
hex = { workspace = true }
humansize = { workspace = true }
imbl = { workspace = true }
metrics = { path = "../metrics" }
paste = { workspace = true }
proptest = { workspace = true, optional = true }
proptest-derive = { workspace = true, optional = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
sync_types = { package = "convex_sync_types", path = "../convex/sync_types" }
thiserror = { workspace = true }
tokio = { workspace = true }
uuid = { workspace = true }

[target.'cfg(not(target_os="windows"))'.dependencies]
sha2 = { workspace = true, features = ["asm"] }

[dev-dependencies]
# We only use `base32` in tests for checking that our custom implementation matches. We diverge from
# `base32` by using lowercase characters and not being permissive while decoding.
base32 = { workspace = true }
cmd_util = { path = "../cmd_util" }
convex = { path = "../convex", features = ["testing"] }
criterion = { workspace = true }
errors = { path = "../errors", features = ["testing"] }
metrics = { path = "../metrics", features = ["testing"] }
proptest = { workspace = true }
proptest-derive = { workspace = true }
sync_types = { package = "convex_sync_types", path = "../convex/sync_types", features = [
    "testing",
] }

[features]
testing = [
    "errors/testing",
    "metrics/testing",
    "proptest",
    "proptest-derive",
    "sync_types/testing",
]

[[bench]]
name = "document_id"
harness = false
