[package]
name = "shape_inference"
version = "0.1.0"
authors = ["Convex, Inc. <team@convex.dev>"]
edition = "2021"
license = "LicenseRef-FSL-1.1-Apache-2.0"

[lib]
doctest = false

[dependencies]
anyhow = { workspace = true }
base64 = { workspace = true }
itertools = { workspace = true }
maplit = { workspace = true }
proptest = { workspace = true, optional = true }
serde = { workspace = true }
serde_json = { workspace = true }
value = { path = "../value" }

[dev-dependencies]
maplit = { workspace = true }
proptest = { workspace = true }
sync_types = { package = "convex_sync_types", path = "../convex/sync_types" }
value = { path = "../value", features = ["testing"] }

[features]
testing = [
    "proptest",
    "value/testing",
]
