[package]
name = "convex_sync_types"
description = "Sync types for the Convex Websocket protocol (convex.dev)"
version = "0.6.0"
authors = ["Convex, Inc. <no-reply@convex.dev>"]
edition = "2021"
rust-version = "1.65.0"
resolver = "2"
license = "Apache-2.0"
repository = "https://github.com/get-convex/convex-rs"
homepage = "https://www.convex.dev/"

[dependencies]
anyhow = { workspace = true }
base64 = { workspace = true }
derive_more = { workspace = true }
headers = { workspace = true }
proptest = { workspace = true, optional = true }
proptest-derive = { workspace = true, optional = true }
rand = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = ["float_roundtrip", "preserve_order"] }
uuid = { workspace = true, features = ["serde", "v4"] }

[dev-dependencies]
proptest = { workspace = true }
proptest-derive = { workspace = true }

[features]
testing = ["proptest", "proptest-derive"]
