[package]
name = "text_search"
version = "0.1.0"
edition = "2024"
license = "LicenseRef-FSL-1.1-Apache-2.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
doctest = false

[features]
testing = ["common/testing", "metrics/testing", "proptest", "value/testing"]

[dependencies]
anyhow = { workspace = true }
byteorder = { workspace = true }
common = { workspace = true }
fastrace = { workspace = true }
maplit = { workspace = true }
metrics = { workspace = true }
proptest = { workspace = true, optional = true }
sucds = { workspace = true }
tantivy = { workspace = true }
tantivy-common = { workspace = true }
value = { workspace = true }

[dev-dependencies]
cmd_util = { workspace = true }
common = { workspace = true, features = ["testing"] }
metrics = { workspace = true, features = ["testing"] }
proptest = { workspace = true }
value = { workspace = true, features = ["testing"] }

[lints]
workspace = true
