[package]
name = "text_search"
version = "0.1.0"
edition = "2021"
license = "LicenseRef-FSL-1.1-Apache-2.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
doctest = false

[dependencies]
anyhow = { workspace = true }
byteorder = { workspace = true }
common = { path = "../common" }
maplit = { workspace = true }
metrics = { path = "../metrics" }
minitrace = { workspace = true }
proptest = { workspace = true, optional = true }
proptest-derive = { workspace = true, optional = true }
sucds = { workspace = true }
tantivy = { workspace = true }
tantivy-common = { workspace = true }
value = { path = "../value" }

[dev-dependencies]
common = { path = "../common", features = ["testing"] }
metrics = { path = "../metrics", features = ["testing"] }
proptest = { workspace = true }
proptest-derive = { workspace = true }
value = { path = "../value", features = ["testing"] }

[features]
testing = [
    "common/testing",
    "metrics/testing",
    "proptest",
    "proptest-derive",
    "value/testing"
]
