[package]
name = "packed_value"
version = "0.1.0"
authors = ["Convex, Inc. <no-reply@convex.dev>"]
edition = "2021"
license = "LicenseRef-FSL-1.1-Apache-2.0"

[lib]
doctest = false

[dependencies]
anyhow = { workspace = true }
base64 = { workspace = true }
bytes = { workspace = true }
flexbuffers = { workspace = true }
proptest = { workspace = true, optional = true }
serde = { workspace = true }
serde_json = { workspace = true }
value = { path = "../value" }

[dev-dependencies]
cmd_util = { path = "../cmd_util" }
criterion = { workspace = true }
maplit = { workspace = true }
proptest = { workspace = true }
value = { path = "../value", features = ["testing"] }

[features]
testing = [
    "proptest",
    "value/testing",
]

[[bench]]
name = "packed_value"
harness = false
