[env]
CARGO_WORKSPACE_ROOT = { value = "", relative = true }
CHRONO_TZ_TIMEZONE_FILTER = "US/Pacific"

[target.aarch64-unknown-linux-gnu]
rustflags = ["-Ctarget-cpu=neoverse-n1", "-Anon_local_definitions"]

[target.aarch64-apple-darwin]
rustflags = ["-Ctarget-cpu=apple-m1", "-Anon_local_definitions"]

[target.x86_64-pc-windows-msvc]
# FORCE:MULTIPLE is a bit sketchy. v8 and rocksdb both export the same symbol.
# This seems to work around it to build on windows, but it's not ideal.
rustflags = ["-Clink-arg=/FORCE:MULTIPLE", "-Clink-arg=/STACK:4194304", "-Anon_local_definitions"]

[target.'cfg(all())']
rustflags = ["--cfg", "tokio_unstable", "-Anon_local_definitions"]

[net]
git-fetch-with-cli = true
