[package]
name = "storage_zip_reader"
version = "0.1.0"
authors = ["Convex, Inc. <no-reply@convex.dev>"]
edition = "2021"
license = "LicenseRef-FSL-1.1-Apache-2.0"

[lib]
doctest = false

[features]
testing = ["common/testing", "errors/testing", "storage/testing"]

[dependencies]
anyhow = { workspace = true }
bytes = { workspace = true }
common = { workspace = true }
errors = { workspace = true }
futures = { workspace = true }
rc-zip = { workspace = true }
storage = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }

[dev-dependencies]
async_zip = { workspace = true }
async_zip_0_0_9 = { workspace = true }
aws_s3 = { workspace = true }
common = { workspace = true, features = ["testing"] }
convex_macro = { workspace = true }
errors = { workspace = true, features = ["testing"] }
runtime = { workspace = true }
storage = { workspace = true, features = ["testing"] }
tokio-stream = { workspace = true }

[lints]
workspace = true
