[package]
name = "log_streaming"
version = "0.1.0"
edition = "2024"
license = "LicenseRef-FSL-1.1-Apache-2.0"

[lib]
doctest = false

[features]
testing = [
    "common/testing",
    "database/testing",
    "errors/testing",
    "events/testing",
    "keybroker/testing",
    "metrics/testing",
    "model/testing",
    "runtime/testing",
    "sentry/test",
    "usage_tracking/testing",
]

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
aws-lc-rs = { workspace = true }
bytes = { workspace = true }
common = { workspace = true }
convex_macro = { workspace = true }
database = { workspace = true }
errors = { workspace = true }
events = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
http = { workspace = true }
keybroker = { workspace = true }
maplit = { workspace = true }
metrics = { workspace = true }
model = { workspace = true }
parking_lot = { workspace = true }
reqwest = { workspace = true }
sentry = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
usage_tracking = { workspace = true }

[dev-dependencies]
common = { workspace = true, features = ["testing"] }
database = { workspace = true, features = ["testing"] }
errors = { workspace = true, features = ["testing"] }
events = { workspace = true, features = ["testing"] }
keybroker = { workspace = true, features = ["testing"] }
metrics = { workspace = true, features = ["testing"] }
model = { workspace = true, features = ["testing"] }
runtime = { workspace = true, features = ["testing"] }
sentry = { workspace = true, features = ["test"] }
usage_tracking = { workspace = true, features = ["testing"] }

[lints]
workspace = true
